#!/bin/sh
# Code generated by servicegen. DO NOT EDIT.
set -eu

retry_command=0
retry_default_attempts=10
if [ "${1:-}" = "--retry" ]; then
  retry_command=1
  shift
fi

# GNU Make invokes its configured SHELL with `-c` as the first argument.
# Docker passes the real shell explicitly through its JSON SHELL instruction.
if [ "${1:-}" = "-c" ]; then
  set -- /bin/sh "$@"
fi

# APT metadata and package files may change between `apt-get update` and
# `apt-get install` on an upstream mirror. Retry the complete transaction so a
# failed install refreshes the index from the same configured source. Keep this
# policy here so every generated language and Docker stage behaves alike.
if [ "$retry_command" -eq 0 ] \
    && [ "${1:-}" = "/bin/sh" ] \
    && [ "${2:-}" = "-c" ]; then
  case "${3:-}" in
    *"apt-get update"*) retry_command=1 ;;
    *"pnpm install"*) retry_command=1 ;;
    *"docker build "*) retry_command=1 ;;
    *"docker buildx build "*) retry_command=1 ;;
    *"docker compose "*" build"*) retry_command=1 ;;
  esac
fi

# Values from the user-owned override file take precedence over the generated
# catalog. `env` accepts downloader variable names that are not shell identifiers.
default_overrides=/etc/servicegen/dependency-download-mirrors.env
default_catalog=/etc/servicegen/dependency-download-mirrors.generated.env
if [ -f ./dependency-download-mirrors.env ]; then
  default_overrides=./dependency-download-mirrors.env
fi
if [ -f ./dependency-download-mirrors.generated.env ]; then
  default_catalog=./dependency-download-mirrors.generated.env
fi
for file in \
  "${DEPENDENCY_DOWNLOAD_MIRROR_OVERRIDES:-$default_overrides}" \
  "${DEPENDENCY_DOWNLOAD_MIRROR_CATALOG:-$default_catalog}"; do
  [ -f "$file" ] || continue
  while IFS= read -r line || [ -n "$line" ]; do
    case "$line" in ''|'#'*) continue ;; esac
    case "$line" in
      *=*) ;;
      *) echo "invalid dependency mirror assignment in $file: $line" >&2; exit 2 ;;
    esac
    key=${line%%=*}
    value=${line#*=}
    prefix='${DEPENDENCY_GITHUB_RAW_URL}'
    case "$value" in
      "$prefix"*)
        value="${DEPENDENCY_GITHUB_RAW_URL:-https://github.com}${value#"$prefix"}"
        ;;
    esac
    set -- "$key=$value" "$@"
  done <"$file"
done

if [ "$retry_command" -eq 0 ]; then
  exec env "$@"
fi

attempt=1
max_attempts=${DEPENDENCY_COMMAND_RETRY_ATTEMPTS:-$retry_default_attempts}
retry_delay=${DEPENDENCY_COMMAND_RETRY_DELAY_SECONDS:-5}
while :; do
  if env "$@"; then
    exit 0
  else
    status=$?
  fi
  if [ "$attempt" -ge "$max_attempts" ]; then
    exit "$status"
  fi
  echo "dependency command failed (exit $status); retry $attempt/$max_attempts in ${retry_delay}s" >&2
  sleep "$retry_delay"
  attempt=$((attempt + 1))
done