#!/bin/sh
# Code generated by servicegen. DO NOT EDIT.
set -eu

default_overrides=/etc/servicegen/dependency-download-mirrors.env
default_catalog=/etc/servicegen/dependency-download-mirrors.generated.env
for file in \
  "${DEPENDENCY_DOWNLOAD_MIRROR_OVERRIDES:-$default_overrides}" \
  "${DEPENDENCY_DOWNLOAD_MIRROR_CATALOG:-$default_catalog}"; do
  [ -f "$file" ] || continue
  while IFS= read -r line || [ -n "$line" ]; do
    case "$line" in ''|'#'*) continue ;; esac
    case "$line" in
      *=*) ;;
      *) echo "invalid dependency mirror assignment in $file: $line" >&2; exit 2 ;;
    esac
    key=${line%%=*}
    value=${line#*=}
    prefix='${DEPENDENCY_GITHUB_RAW_URL}'
    case "$value" in
      "$prefix"*)
        value="${DEPENDENCY_GITHUB_RAW_URL:-https://github.com}${value#"$prefix"}"
        ;;
    esac
    set -- "$key=$value" "$@"
  done <"$file"
done

exec env "$@"
